ARG CUDA_BASE_TAG=12.6.2-cudnn-devel-ubuntu22.04
FROM nvcr.io/nvidia/cuda:${CUDA_BASE_TAG}

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV ROS_DISTRO=humble
ENV CONDA_DIR=/opt/conda

SHELL ["/bin/bash", "-lc"]

RUN apt-get update && apt-get install -y \
    locales tzdata \
    curl wget ca-certificates gnupg2 lsb-release software-properties-common \
    build-essential cmake pkg-config git vim tmux \
    python3-pip python3-dev python3-venv python3-empy \
    iputils-ping net-tools usbutils udev \
    libopenblas-dev \
    libboost-all-dev \
    libeigen3-dev libyaml-cpp-dev libsparsehash-dev \
    libgl1 libglib2.0-0 libsm6 libxext6 libxrender1 ffmpeg \
    && locale-gen en_US en_US.UTF-8 \
    && update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

RUN add-apt-repository universe
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
      -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu jammy main" \
      > /etc/apt/sources.list.d/ros2.list && \
    apt-get update && apt-get install -y \
      ros-humble-ros-base \
      ros-humble-cv-bridge \
      ros-humble-rmw-cyclonedds-cpp \
      ros-humble-robot-state-publisher \
      ros-humble-tf2-ros \
      ros-humble-xacro \
      python3-colcon-common-extensions \
      python3-rosdep \
      python3-vcstool \
      && rm -rf /var/lib/apt/lists/*

RUN rosdep init || true

WORKDIR /opt/asv

COPY src/ /opt/asv/src/
COPY urdf/ /opt/asv/urdf/
COPY docker/entrypoint.sh /entrypoint.sh
COPY scripts/ /opt/asv/scripts/

RUN chmod +x /entrypoint.sh /opt/asv/scripts/*.sh

RUN cd /opt/asv/src/ASV_localization && \
    mkdir -p build && cd build && \
    cmake .. && make -j"$(nproc)" && make install

RUN source /opt/ros/humble/setup.bash && \
    export PATH=/usr/bin:/bin:$PATH && \
    which python3 && python3 --version && \
    cd /opt/asv/src/ASV_localization/ROS2/drift_ros2/src/custom_sensor_msgs && \
    colcon build --packages-select custom_sensor_msgs \
      --cmake-args -DPython3_EXECUTABLE=/usr/bin/python3 -DPYTHON_EXECUTABLE=/usr/bin/python3 && \
    source install/setup.bash && \
    cd ../.. && \
    colcon build --symlink-install \
      --cmake-args -DPython3_EXECUTABLE=/usr/bin/python3 -DPYTHON_EXECUTABLE=/usr/bin/python3

RUN wget -qO /tmp/miniforge.sh \
      https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh && \
    bash /tmp/miniforge.sh -b -p ${CONDA_DIR} && \
    rm -f /tmp/miniforge.sh

RUN /opt/conda/bin/conda config --system --add channels conda-forge && \
    /opt/conda/bin/conda config --system --set channel_priority strict && \
    /opt/conda/bin/conda config --system --set auto_activate_base false && \
    /opt/conda/bin/conda update -n base -y conda mamba

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]
