#!/bin/bash
set -e

source /opt/ros/humble/setup.bash
source /opt/asv/src/ASV_localization/ROS2/drift_ros2/install/setup.bash

TIMESTAMP_AUDIT_OUTPUT_DIR="${TIMESTAMP_AUDIT_OUTPUT_DIR:-}"
TIMESTAMP_AUDIT_HISTORY_SIZE="${TIMESTAMP_AUDIT_HISTORY_SIZE:-2000}"
TIMESTAMP_AUDIT_SUMMARY_WINDOW_SIZE="${TIMESTAMP_AUDIT_SUMMARY_WINDOW_SIZE:-500}"
TIMESTAMP_AUDIT_SUMMARY_PERIOD_SEC="${TIMESTAMP_AUDIT_SUMMARY_PERIOD_SEC:-5.0}"
TIMESTAMP_AUDIT_GENERAL_PAIR_WINDOW_MS="${TIMESTAMP_AUDIT_GENERAL_PAIR_WINDOW_MS:-250.0}"
TIMESTAMP_AUDIT_COMMAND_PAIR_WINDOW_MS="${TIMESTAMP_AUDIT_COMMAND_PAIR_WINDOW_MS:-2000.0}"

TIMESTAMP_AUDIT_LIDAR_TOPIC="${TIMESTAMP_AUDIT_LIDAR_TOPIC:-/sensors/lidar/points}"
TIMESTAMP_AUDIT_LIDAR_MSG_TYPE="${TIMESTAMP_AUDIT_LIDAR_MSG_TYPE:-sensor_msgs/msg/PointCloud2}"
TIMESTAMP_AUDIT_CAMERA_TOPIC="${TIMESTAMP_AUDIT_CAMERA_TOPIC:-/sensors/camera/color/image_raw}"
TIMESTAMP_AUDIT_CAMERA_MSG_TYPE="${TIMESTAMP_AUDIT_CAMERA_MSG_TYPE:-sensor_msgs/msg/Image}"
TIMESTAMP_AUDIT_POSE_TOPIC="${TIMESTAMP_AUDIT_POSE_TOPIC:-/gt_pose}"
TIMESTAMP_AUDIT_POSE_MSG_TYPE="${TIMESTAMP_AUDIT_POSE_MSG_TYPE:-geometry_msgs/msg/PoseStamped}"
TIMESTAMP_AUDIT_IMU_TOPIC="${TIMESTAMP_AUDIT_IMU_TOPIC:-/vectornav/imu}"
TIMESTAMP_AUDIT_IMU_MSG_TYPE="${TIMESTAMP_AUDIT_IMU_MSG_TYPE:-sensor_msgs/msg/Imu}"
TIMESTAMP_AUDIT_STATE_TWIST_TOPIC="${TIMESTAMP_AUDIT_STATE_TWIST_TOPIC:-/wamv/inekf_odom_correction/twist}"
TIMESTAMP_AUDIT_STATE_TWIST_MSG_TYPE="${TIMESTAMP_AUDIT_STATE_TWIST_MSG_TYPE:-geometry_msgs/msg/TwistStamped}"
TIMESTAMP_AUDIT_COMMAND_TOPIC="${TIMESTAMP_AUDIT_COMMAND_TOPIC:-}"
TIMESTAMP_AUDIT_COMMAND_MSG_TYPE="${TIMESTAMP_AUDIT_COMMAND_MSG_TYPE:-geometry_msgs/msg/TwistStamped}"

export PYTHONUNBUFFERED=1

ros_args=(
  --ros-args
  -p "history_size:=${TIMESTAMP_AUDIT_HISTORY_SIZE}"
  -p "summary_window_size:=${TIMESTAMP_AUDIT_SUMMARY_WINDOW_SIZE}"
  -p "summary_period_sec:=${TIMESTAMP_AUDIT_SUMMARY_PERIOD_SEC}"
  -p "general_pair_window_ms:=${TIMESTAMP_AUDIT_GENERAL_PAIR_WINDOW_MS}"
  -p "command_pair_window_ms:=${TIMESTAMP_AUDIT_COMMAND_PAIR_WINDOW_MS}"
  -p "lidar_topic:=${TIMESTAMP_AUDIT_LIDAR_TOPIC}"
  -p "lidar_msg_type:=${TIMESTAMP_AUDIT_LIDAR_MSG_TYPE}"
  -p "camera_topic:=${TIMESTAMP_AUDIT_CAMERA_TOPIC}"
  -p "camera_msg_type:=${TIMESTAMP_AUDIT_CAMERA_MSG_TYPE}"
  -p "pose_topic:=${TIMESTAMP_AUDIT_POSE_TOPIC}"
  -p "pose_msg_type:=${TIMESTAMP_AUDIT_POSE_MSG_TYPE}"
  -p "imu_topic:=${TIMESTAMP_AUDIT_IMU_TOPIC}"
  -p "imu_msg_type:=${TIMESTAMP_AUDIT_IMU_MSG_TYPE}"
  -p "state_twist_topic:=${TIMESTAMP_AUDIT_STATE_TWIST_TOPIC}"
  -p "state_twist_msg_type:=${TIMESTAMP_AUDIT_STATE_TWIST_MSG_TYPE}"
)

if [ -n "${TIMESTAMP_AUDIT_OUTPUT_DIR}" ]; then
  ros_args+=(-p "output_dir:=${TIMESTAMP_AUDIT_OUTPUT_DIR}")
fi

if [ -n "${TIMESTAMP_AUDIT_COMMAND_TOPIC}" ]; then
  ros_args+=(
    -p "command_topic:=${TIMESTAMP_AUDIT_COMMAND_TOPIC}"
    -p "command_msg_type:=${TIMESTAMP_AUDIT_COMMAND_MSG_TYPE}"
  )
fi

exec python3 /opt/asv/scripts/timestamp_audit.py "${ros_args[@]}"
