#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
COMPOSE_FILE="${COMPOSE_FILE:-${REPO_ROOT}/docker/compose.jetson.yaml}"
CONTAINER_NAME="${CONTAINER_NAME:-asv_dev}"
TIMESTAMP_AUDIT_COMMAND="${TIMESTAMP_AUDIT_COMMAND:-/opt/asv/scripts/run_timestamp_audit.sh}"

TIMESTAMP_AUDIT_RUN_ID="${TIMESTAMP_AUDIT_RUN_ID:-$(date +%Y%m%d_%H%M%S)}"
TIMESTAMP_AUDIT_OUTPUT_ROOT="${TIMESTAMP_AUDIT_OUTPUT_ROOT:-${REPO_ROOT}/logs/timestamp_audit}"
HOST_OUTPUT_DIR="${TIMESTAMP_AUDIT_OUTPUT_ROOT}/${TIMESTAMP_AUDIT_RUN_ID}"
TIMESTAMP_AUDIT_OUTPUT_DIR="${TIMESTAMP_AUDIT_OUTPUT_DIR:-/opt/asv/logs/timestamp_audit/${TIMESTAMP_AUDIT_RUN_ID}}"

TIMESTAMP_AUDIT_HISTORY_SIZE="${TIMESTAMP_AUDIT_HISTORY_SIZE:-2000}"
TIMESTAMP_AUDIT_SUMMARY_WINDOW_SIZE="${TIMESTAMP_AUDIT_SUMMARY_WINDOW_SIZE:-500}"
TIMESTAMP_AUDIT_SUMMARY_PERIOD_SEC="${TIMESTAMP_AUDIT_SUMMARY_PERIOD_SEC:-5.0}"
TIMESTAMP_AUDIT_GENERAL_PAIR_WINDOW_MS="${TIMESTAMP_AUDIT_GENERAL_PAIR_WINDOW_MS:-250.0}"
TIMESTAMP_AUDIT_COMMAND_PAIR_WINDOW_MS="${TIMESTAMP_AUDIT_COMMAND_PAIR_WINDOW_MS:-2000.0}"

TIMESTAMP_AUDIT_LIDAR_TOPIC="${TIMESTAMP_AUDIT_LIDAR_TOPIC:-/sensors/lidar/points}"
TIMESTAMP_AUDIT_LIDAR_MSG_TYPE="${TIMESTAMP_AUDIT_LIDAR_MSG_TYPE:-sensor_msgs/msg/PointCloud2}"
TIMESTAMP_AUDIT_CAMERA_TOPIC="${TIMESTAMP_AUDIT_CAMERA_TOPIC:-/sensors/camera/color/image_raw}"
TIMESTAMP_AUDIT_CAMERA_MSG_TYPE="${TIMESTAMP_AUDIT_CAMERA_MSG_TYPE:-sensor_msgs/msg/Image}"
TIMESTAMP_AUDIT_POSE_TOPIC="${TIMESTAMP_AUDIT_POSE_TOPIC:-/gt_pose}"
TIMESTAMP_AUDIT_POSE_MSG_TYPE="${TIMESTAMP_AUDIT_POSE_MSG_TYPE:-geometry_msgs/msg/PoseStamped}"
TIMESTAMP_AUDIT_IMU_TOPIC="${TIMESTAMP_AUDIT_IMU_TOPIC:-/vectornav/imu}"
TIMESTAMP_AUDIT_IMU_MSG_TYPE="${TIMESTAMP_AUDIT_IMU_MSG_TYPE:-sensor_msgs/msg/Imu}"
TIMESTAMP_AUDIT_STATE_TWIST_TOPIC="${TIMESTAMP_AUDIT_STATE_TWIST_TOPIC:-/wamv/inekf_odom_correction/twist}"
TIMESTAMP_AUDIT_STATE_TWIST_MSG_TYPE="${TIMESTAMP_AUDIT_STATE_TWIST_MSG_TYPE:-geometry_msgs/msg/TwistStamped}"
TIMESTAMP_AUDIT_COMMAND_TOPIC="${TIMESTAMP_AUDIT_COMMAND_TOPIC:-}"
TIMESTAMP_AUDIT_COMMAND_MSG_TYPE="${TIMESTAMP_AUDIT_COMMAND_MSG_TYPE:-geometry_msgs/msg/TwistStamped}"

mkdir -p "${HOST_OUTPUT_DIR}"

echo "Writing timestamp audit logs to ${HOST_OUTPUT_DIR}" >&2

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is not installed on this host." >&2
  exit 1
fi

docker compose -f "${COMPOSE_FILE}" up -d

exec docker exec -it \
  -e TIMESTAMP_AUDIT_OUTPUT_DIR="${TIMESTAMP_AUDIT_OUTPUT_DIR}" \
  -e TIMESTAMP_AUDIT_HISTORY_SIZE="${TIMESTAMP_AUDIT_HISTORY_SIZE}" \
  -e TIMESTAMP_AUDIT_SUMMARY_WINDOW_SIZE="${TIMESTAMP_AUDIT_SUMMARY_WINDOW_SIZE}" \
  -e TIMESTAMP_AUDIT_SUMMARY_PERIOD_SEC="${TIMESTAMP_AUDIT_SUMMARY_PERIOD_SEC}" \
  -e TIMESTAMP_AUDIT_GENERAL_PAIR_WINDOW_MS="${TIMESTAMP_AUDIT_GENERAL_PAIR_WINDOW_MS}" \
  -e TIMESTAMP_AUDIT_COMMAND_PAIR_WINDOW_MS="${TIMESTAMP_AUDIT_COMMAND_PAIR_WINDOW_MS}" \
  -e TIMESTAMP_AUDIT_LIDAR_TOPIC="${TIMESTAMP_AUDIT_LIDAR_TOPIC}" \
  -e TIMESTAMP_AUDIT_LIDAR_MSG_TYPE="${TIMESTAMP_AUDIT_LIDAR_MSG_TYPE}" \
  -e TIMESTAMP_AUDIT_CAMERA_TOPIC="${TIMESTAMP_AUDIT_CAMERA_TOPIC}" \
  -e TIMESTAMP_AUDIT_CAMERA_MSG_TYPE="${TIMESTAMP_AUDIT_CAMERA_MSG_TYPE}" \
  -e TIMESTAMP_AUDIT_POSE_TOPIC="${TIMESTAMP_AUDIT_POSE_TOPIC}" \
  -e TIMESTAMP_AUDIT_POSE_MSG_TYPE="${TIMESTAMP_AUDIT_POSE_MSG_TYPE}" \
  -e TIMESTAMP_AUDIT_IMU_TOPIC="${TIMESTAMP_AUDIT_IMU_TOPIC}" \
  -e TIMESTAMP_AUDIT_IMU_MSG_TYPE="${TIMESTAMP_AUDIT_IMU_MSG_TYPE}" \
  -e TIMESTAMP_AUDIT_STATE_TWIST_TOPIC="${TIMESTAMP_AUDIT_STATE_TWIST_TOPIC}" \
  -e TIMESTAMP_AUDIT_STATE_TWIST_MSG_TYPE="${TIMESTAMP_AUDIT_STATE_TWIST_MSG_TYPE}" \
  -e TIMESTAMP_AUDIT_COMMAND_TOPIC="${TIMESTAMP_AUDIT_COMMAND_TOPIC}" \
  -e TIMESTAMP_AUDIT_COMMAND_MSG_TYPE="${TIMESTAMP_AUDIT_COMMAND_MSG_TYPE}" \
  "${CONTAINER_NAME}" \
  bash -lc "${TIMESTAMP_AUDIT_COMMAND}"
